language: node_js
node_js:
  - 10

branches:
  only:
    - master
env:
  - secure: "fH5YvFb8HTEQ40WlkAhlMK0/6zdOlzyzRWVqH2g1cGzfCwzuu4mFQ3oa4KpLQlOxmyh5XjQ7sQOLenTp9twBuINX2qQFAEVGkvPxoDU9EhMJKUE5wu+ES3Djj6Z/WZLYTsyQxUE1A/8TXhfRjkAVXo5i7RwdsdYSsrA7YaBcyUN93pzKd1L4nC+3q90jUfokyK3KRbPROO8+vs6709FfrESbxTCW8p/jBRsk9QBhB150H4pzbDzR7xPLytJul4XyMXZViNm+ui/ede5dLRObNIIem5I6qtA38oxOlEnZ2zyEfIHD4jOcDVVPxG5sKCUUFniSo9IhKG/J0OiLR+k2oklDZbsKl+1c90Z3QsgJmYGQndU8aHyt4soKlnWpW55bwzkyVJ/SLBt0PaH+w/X1ms2bSZqhS32KH1l4+AXx4/16yC0X4JMEC6g1qStQdVXX7WRZNRfZLNdBnTd3CwBBgeLQ9P5F6aMHBbDz5L9z19hdb8zlHYyGYgL72ae0f8qTwoIWVAs7pYPWhq3wilIRERe/4Js+8+cTCy6e5OFv9LWxnOWCPUfc2G9NVk1lDseDW5yWS8OlqOPsNWfmyF+UyudCAB85GFgP/nqGTC5kXgCl2f2G6poq+4JTR27ChwthFSxal+kUEkTboxk7v2309unKOpHUDrPRG3/boiW4oKM="

before_script:
  - npm install grunt-cli -g
script: chmod +x ./jsdoc.sh; ./jsdoc.sh
