language: node_js
node_js:
  - 10

branches:
  only:
    - master
env:
  - secure: "DiPNMG82aDqCUiall19IEEfdQVmNOA6FIZcnYsB08PYWQb2jA9lT7oQ0ElwkWho3Eo6qQioyfInNPctfN17K5kHwjFijxzPJiz04mBoPoa6DizlKSoldpE6xU/czPM6UyFVgIuu1nwpkMdg4VL1B9RLrB6X6wTxcAColKtH9iNmrygkmNw5Ub2TV47vmX93FCBNJiiefuDYBjAyl9jjzDGFhAs7g7F10h/QQgLfU0QZA/qZMXuhJLiQT1bZcNhIkFPJ7ypWmNRzDUH1dKkgM1pXAjxskqe6nSpQPRkDaFmqWfzf1e2a/sHX2ZhejdguMqZM6zbDgzK8U6HRTANXOWV5t3842K2RJW3uHnazHYDasjSJmcLTH5VOLpFGZdqL9dfO1JUO8xsYRrBM0uy8EdESoOr91Lq1u0j67E5ysn/9HJ1mVXN0NVJNioxczHMoBno6UKpUqAcTofAm4NFMQiO4kEqLLWeyLeFwYr3j+uzXukLcmJ3uYTFGtlATy2zUQF8vOz7djdXLH8IXL1dJay2hhQUV4mkFv7hjPuSErq2ePc8wM6L0jDlbfMeAF7pTtHTc/HnImOh7yObKHoezLWD/fBjHTfDzUCmb/jKtf9/rIxbMhjnGAkHERYbF6avoBv/DAWAxFthXCNwhssqXSL6mDBS74Erni7au5Dy2dlxA="

before_script:
  - npm install grunt-cli -g
script: ./.github/jsdoc.sh
