environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'

  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: AzEW4hOZq5g/mcqSqPjuWpYRhw7i5NuPtaAg5ZjQOj8nmC0gFpT6ZolUZFy5uI/g

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install grunt-cli -g
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - ps: If ($env:nodejs_version -eq 10) {npm run coverage}

build: off
