environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install grunt-cli -g
  - npm install

test_script:
  - node --version
  - npm --version
  - grunt test
